<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Kapitel 11 Lineare Regression | Datenanalyse mit R</title>
<meta name="author" content="Christina Bogner">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.2"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.9/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.2.5.1/tabs.js"></script><script src="libs/bs3compat-0.2.5.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.jquery.min.js"></script><script src="https://cdn.jsdelivr.net/npm/mark.js@8.11.1/dist/mark.min.js"></script><!-- CSS --><link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="font-awesome.min.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="SoSe 2021">Datenanalyse mit R</a>:
        <small class="text-muted">SoSe 2021</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Vorwort</a></li>
<li><a class="" href="einfuehrung.html"><span class="header-section-number">1</span> Der Kurs</a></li>
<li><a class="" href="erste-schritte.html"><span class="header-section-number">2</span> Erste Schritte in R</a></li>
<li><a class="" href="reproduzieren.html"><span class="header-section-number">3</span> R Markdown</a></li>
<li><a class="" href="ggplot.html"><span class="header-section-number">4</span> Einführung in ggplot2</a></li>
<li><a class="" href="daten-einlesen-und-visualisieren.html"><span class="header-section-number">5</span> Daten einlesen und visualisieren</a></li>
<li><a class="" href="tidyverse.html"><span class="header-section-number">6</span> Der explorative Workflow mit tidyverse</a></li>
<li><a class="" href="stichproben.html"><span class="header-section-number">7</span> Stichproben und Variabilität</a></li>
<li><a class="" href="bootstrapping-und-konfidenzintervalle.html"><span class="header-section-number">8</span> Bootstrapping und Konfidenzintervalle</a></li>
<li><a class="" href="hypothesentsts.html"><span class="header-section-number">9</span> Hypothesentests mit dem Paket infer</a></li>
<li><a class="" href="effekte.html"><span class="header-section-number">10</span> Schätzen von Effekten: Raus aus der \(p &lt; 0.05\)-Falle</a></li>
<li><a class="active" href="regression.html"><span class="header-section-number">11</span> Lineare Regression</a></li>
<li><a class="" href="regression-inferenz.html"><span class="header-section-number">12</span> Inferenz in linearer Regression</a></li>
<li><a class="" href="daten-und-bericht.html"><span class="header-section-number">13</span> Datenquellen und Struktur des Abschlussberichts</a></li>
<li><a class="" href="aufgabensammlung.html"><span class="header-section-number">14</span> Aufgabensammlung</a></li>
<li><a class="" href="literatur.html">Literatur</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/ChrisBogner/datenanalyse">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="regression" class="section level1" number="11">
<h1>
<span class="header-section-number">Kapitel 11</span> Lineare Regression<a class="anchor" aria-label="anchor" href="#regression"><i class="fas fa-link"></i></a>
</h1>
<div class="rmdoutcomes">
<ul>
<li>
allgemeinen Aufbau eines Regressionsmodells erklären
</li>
<li>
Annahmen der linearen Normalregression benennen
</li>
<li>
einfache lineare Regression selbst in R durchführen
</li>
</ul>
</div>
<p>In diesem Kapitel werden wir in die statistische Modellierung einsteigen. Bisher haben Sie gelernt, wie man mit Hilfe von modernen Resamplingverfahren oder Simulationen Hypothesentests durchführt und Konfidenzintervalle berechnet. Wir werden in späteren Kapiteln auch für die Modellierung Bootstrap verwenden.</p>
<p>Es gibt im wesentlichen zwei Gründe, warum man modelliert.</p>
<ol style="list-style-type: decimal">
<li>Wir vermuten einen Zusammenhang zwischen Variablen und wollen diesen überprüfen (explikatives Modellieren).</li>
<li>Wir wollen ein Modell zur Vorhersage entwickeln (prädiktives Modellieren).</li>
</ol>
<p>Wir werden uns in diesem Kurs nur mit dem explikativen (erklärenden) Modellieren beschäftigen.</p>
<div id="begriff-regression" class="section level2" number="11.1">
<h2>
<span class="header-section-number">11.1</span> Begriff Regression<a class="anchor" aria-label="anchor" href="#begriff-regression"><i class="fas fa-link"></i></a>
</h2>
<p>Woher kommt der Begriff <em>Regression</em>? Diesen prägte Sir Francis Galdon (1822-1911) <span class="citation">(<a href="literatur.html#ref-Fahrmeir2009" role="doc-biblioref">Fahrmeir, Kneib, and Lang 2009</a>)</span>. Galton interessierte sich unter anderem für den Zusammenhang zwischen der durchschnittlichen Körpergröße der Eltern und der Körpergröße ihrer erwachsenen Kinder. Leider war er nicht nur einer der Väter der Statistik, sondern auch ein Rassist.</p>
<p>Galton stellte fest, dass Kinder von unterdurchschnittlich kleinen Eltern eher größer waren und umgekehrt, Kinder von überdurchschnittlich großen Eltern eher kleiner waren. Diesen Effekt nannte er Regression (Rückkehr) zur Mitte.</p>
</div>
<div id="idee-der-regression" class="section level2" number="11.2">
<h2>
<span class="header-section-number">11.2</span> Idee der Regression<a class="anchor" aria-label="anchor" href="#idee-der-regression"><i class="fas fa-link"></i></a>
</h2>
<p>Die Regression ist ein Modell, dass einen Zusammenhang zwischen Variablen analysiert. Wenn dieser Zusammenhang linear ist, dann nennt man das Modell <strong>lineare Regression</strong>. Wir werden uns ausschließlich mit solchen linearen Modellen beschäftigen.</p>
<p>Die lineare Regression untersucht also den <strong>linearen Zusammenhang</strong> zwischen den sogen. <strong>erklärenden Variablen</strong> und der <strong>Zielvariablen</strong>. Im historischen Beispiel von Galton gab es nur eine erklärende Variable, nämlich die Durchschnittsgröße der Eltern. Die Zielvariable war die zu erwartende Größe der Kinder. Es ging also nicht darum, die exakte Größe eines bestimmten Kindes zu berechnen, sondern den Einfluss der Durchschnittsgröße der Eltern auf die <strong>zu erwartende</strong> Größe der Kinder. Es ging also um den <strong>systematischen Einfluss</strong>, nicht um bestimmte Eltern-Kind-Paare. Diese waren nur Stichproben. Spätestens hier sollte es klingeln, denn die Größe der Kinder ist somit eine <strong>Zufallsvariable</strong>.</p>
<p>Die Zielvariable muss nicht immer stetig wie die Körpergröße sein. Sie kann binär, kategorial oder eine Zählvariable sein. Auch die erklärenden Variablen können stetig, binär oder kategorial sein. Das macht die Regessionsmodelle sehr divers. Wir werden uns im Wesentlichen mit numerischen Zielvariablen beschäftigen.</p>
<p>Wir können somit die Regression so zusammenfassen:</p>
<div class="rmddef">
<p>
Die Regression ist ein Modell der Form
</p>
<p>
<span class="math display"><span class="math display">\[y = f(X) + \varepsilon\]</span></span>
</p>
<ul>
<li>
<span class="math inline"><span class="math inline">\(y\)</span></span>: Zielvariable
</li>
<li>
<span class="math inline"><span class="math inline">\(f\)</span></span>: Art des Zusammenhangs
</li>
<li>
<span class="math inline"><span class="math inline">\(X\)</span></span>: Prädiktoren (erklärende Variablen auch Kovariablen)
</li>
<li>
<span class="math inline"><span class="math inline">\(\varepsilon\)</span></span>: Fehlerterm
</li>
</ul>
<p>
Wenn:
</p>
<ul>
<li>
<span class="math inline"><span class="math inline">\(f\)</span></span> linear ist (Einfluss der Prädiktoren addiert sich), spricht man von linearer Regression
</li>
<li>
<span class="math inline"><span class="math inline">\(X\)</span></span> nur ein Prädiktor ist, spricht man von einfacher Regression, sonst von multipler Regression
</li>
</ul>
<p>
Modellkomponenten:
</p>
<ul>
<li>
<span class="math inline"><span class="math inline">\(f(X)\)</span></span>: systematische oder deterministische Komponente
</li>
<li>
<span class="math inline"><span class="math inline">\(\varepsilon\)</span></span>: stochastische Komponente (Störgröße, Fehlerterm)
</li>
</ul>
</div>
<p>Es geht bei der Regression also darum, die systematische Komponente zu modellieren. Der Zusammenhang zwischen Prädiktoren und der Zielvariablen ist nie exakt, es gibt also einen Fehlerterm. Die Zielgröße ist eine Zufallsvariable, deren Verteilung von den Prädiktoren abhängt.</p>
</div>
<div id="einfache-lineare-regression" class="section level2" number="11.3">
<h2>
<span class="header-section-number">11.3</span> Einfache lineare Regression<a class="anchor" aria-label="anchor" href="#einfache-lineare-regression"><i class="fas fa-link"></i></a>
</h2>
<p>Bei einer einfachen linearen Regression gibt es nur einen Prädiktor. Der Zusammenhang zwischen der Zielvariablen und diesem Prädiktor ist linear. Somit hat das Model die Form einer Geraden. Eine Gerade kann man ja mit Hilfe des <span class="math inline">\(y\)</span>-Achsenabschnitts und der Steigung beschreiben. Und genauso sieht das einfache lineare Regressionsmodell aus.</p>
<div class="rmddef">
<p>
Gegeben sind <strong>Datenpaare</strong>: <span class="math inline"><span class="math inline">\((y_i,x_i), \quad i=1,\dots,n\)</span></span> zu metrischen Variablen <span class="math inline"><span class="math inline">\(y\)</span></span> und <span class="math inline"><span class="math inline">\(x\)</span></span>.
</p>
<p>
Das Modell <span class="math display"><span class="math display">\[y_i=\beta_0 + \beta_1x_i + \varepsilon_i, \qquad i=1,\dots,n.\]</span></span> heißt <strong>einfaches lineares Regressionsmodell</strong>, wenn die Fehler <span class="math inline"><span class="math inline">\(\varepsilon_1,\dots, \varepsilon_n\)</span></span> unabhängig und identisch verteilt sind (iid) mit
</p>
<p>
<span class="math display"><span class="math display">\[\mathrm{E}(\varepsilon_i) = 0, \qquad \mathrm{Var}(\varepsilon_i)=\sigma^2.\]</span></span> Wenn zusätzlich gilt <span class="math display"><span class="math display">\[\varepsilon_i \sim N(0,\sigma^2)\]</span></span> d.h. die Residuen normalverteilt sind, sprechen wir von klassischer Normalregression.
</p>
<p>
<span class="math inline"><span class="math inline">\(\beta_0\)</span></span> heißt <span class="math inline"><span class="math inline">\(y\)</span></span>-Achsenabschnitt und <span class="math inline"><span class="math inline">\(\beta_1\)</span></span> Steigung des Modells.
</p>
</div>
<p><span class="math inline">\(\varepsilon_i\)</span> steht für Fehler, die wir im Modell machen. Das sind die Unterschiede, genannt <strong>Residuen</strong>, zwischen dem, was das Modell in dem systematischen Teil (Geradengleichung) <span class="math inline">\(\beta_0 + \beta_1x_i\)</span> ausrechnet und dem tatsächlich gemessenen Wert <span class="math inline">\(y_i\)</span>.</p>
<p><span class="math inline">\(\mathrm{E}\)</span> steht für Erwartungswert. So nennt man den theoretischen Mittelwert einer Zufallsvariablen. Und <span class="math inline">\(\mathrm{Var}\)</span> steht für Varianz. Beim einfachen linearen Regressionsmodell nimmt man also an, dass die Fehler im Mittel Null sind. Sie werden natürlich nie alle Null sein, sondern sie werden variieren. Der Fehlerterm ist also eine Zufallsvariable, dessen Varianz fest sein soll. Eine feste Varianz nennt man Homoskedastizität und die Fehler entsprechend homoskedastisch. Eine Varianz, die schwankt, bezeichnet man als Heteroskedastizität. Das bedeutet unter anderem, dass die Fehler für kleine und große Werte im Modell ähnlich sein müssen. Um auf Galtons Beispiel zurück zu kommen, das Modell soll sowohl die Größe der großen als auch der kleinen Kinder gleich gut erklären.</p>
</div>
<div id="beispiel-zusammenhang-zwischen-der-anreisezeit-und-der-arbeitszeit-in-der-bibliothek" class="section level2" number="11.4">
<h2>
<span class="header-section-number">11.4</span> Beispiel: Zusammenhang zwischen der Anreisezeit und der Arbeitszeit in der Bibliothek<a class="anchor" aria-label="anchor" href="#beispiel-zusammenhang-zwischen-der-anreisezeit-und-der-arbeitszeit-in-der-bibliothek"><i class="fas fa-link"></i></a>
</h2>
<p>Als Beispiel für eine einfache lineare Regression nutzen wir wieder unsere simulierten Daten. Zunächst laden wir die Bibliotheken. Die Bibliothek <code>kntir</code> brauchen wir für das Layouten der Tabellen.</p>
<div class="sourceCode" id="cb173"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/tidymodels/infer">infer</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/moderndive/moderndive/issues">moderndive</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://yihui.org/knitr/">knitr</a></span><span class="op">)</span></code></pre></div>
<p>Wir generieren wieder unsere Liebliengsgrundgesamtheit.</p>
<div class="sourceCode" id="cb174"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span>

<span class="va">student_id</span> <span class="op">&lt;-</span> <span class="fl">1</span><span class="op">:</span><span class="fl">12000</span>
  
<span class="va">anreise</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">12000</span> <span class="op">*</span> <span class="fl">0.8</span>, min <span class="op">=</span> <span class="fl">5</span>, max <span class="op">=</span> <span class="fl">40</span><span class="op">)</span>,
             <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">12000</span> <span class="op">*</span> <span class="fl">0.2</span>, min <span class="op">=</span> <span class="fl">60</span>, max <span class="op">=</span> <span class="fl">120</span><span class="op">)</span><span class="op">)</span>

<span class="va">geschlecht</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'m'</span>, <span class="st">'w'</span><span class="op">)</span>, size <span class="op">=</span> <span class="fl">12000</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>

<span class="va">wohnort</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="va">anreise</span>, <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="op">{</span>
  <span class="kw">if</span><span class="op">(</span><span class="va">x</span> <span class="op">&lt;</span> <span class="fl">30</span><span class="op">)</span> <span class="st">'stadt'</span>
  <span class="kw">else</span> <span class="st">'land'</span>
<span class="op">}</span><span class="op">)</span>

<span class="va">verkehrsmittel</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="va">anreise</span>, <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="op">{</span>
  <span class="kw">if</span><span class="op">(</span><span class="va">x</span> <span class="op">&lt;=</span> <span class="fl">10</span><span class="op">)</span> <span class="st">'zu_fuss'</span>
  <span class="kw">else</span> <span class="kw">if</span><span class="op">(</span><span class="va">x</span> <span class="op">&gt;</span> <span class="fl">10</span> <span class="op">&amp;</span> <span class="va">x</span> <span class="op">&lt;=</span> <span class="fl">15</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'zu_fuss'</span>, <span class="st">'fahrrad'</span><span class="op">)</span>, size <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>
  <span class="kw">else</span> <span class="kw">if</span><span class="op">(</span><span class="va">x</span> <span class="op">&gt;</span> <span class="fl">15</span> <span class="op">&amp;</span> <span class="va">x</span> <span class="op">&lt;=</span> <span class="fl">45</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'bus'</span>, <span class="st">'fahrrad'</span>, <span class="st">'auto'</span><span class="op">)</span>, size <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>
  <span class="kw">else</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'bus'</span>, <span class="st">'auto'</span><span class="op">)</span>, size <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>
<span class="op">}</span><span class="op">)</span>

<span class="va">zeit_bib</span> <span class="op">&lt;-</span> <span class="fl">5</span> <span class="op">*</span> <span class="fl">60</span> <span class="op">-</span> <span class="fl">0.7</span> <span class="op">*</span> <span class="va">anreise</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">anreise</span><span class="op">)</span>, <span class="fl">0</span>, <span class="fl">20</span><span class="op">)</span>

<span class="va">grundgesamtheit</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span><span class="va">student_id</span>, <span class="va">geschlecht</span>, <span class="va">wohnort</span>, <span class="va">verkehrsmittel</span>, <span class="va">anreise</span>, <span class="va">zeit_bib</span><span class="op">)</span>

<span class="va">grundgesamtheit</span></code></pre></div>
<pre><code>## # A tibble: 12,000 x 6
##    student_id geschlecht wohnort verkehrsmittel anreise zeit_bib
##         &lt;int&gt; &lt;chr&gt;      &lt;chr&gt;   &lt;chr&gt;            &lt;dbl&gt;    &lt;dbl&gt;
##  1          1 w          stadt   bus              15.1      294.
##  2          2 w          land    fahrrad          32.6      254.
##  3          3 w          stadt   fahrrad          19.3      231.
##  4          4 m          land    auto             35.9      245.
##  5          5 m          land    bus              37.9      234.
##  6          6 w          stadt   zu_fuss           6.59     303.
##  7          7 w          stadt   bus              23.5      284.
##  8          8 m          land    auto             36.2      274.
##  9          9 m          stadt   fahrrad          24.3      299.
## 10         10 w          stadt   bus              21.0      282.
## # … with 11,990 more rows</code></pre>
<p>Und befragen 200 Studierende.</p>
<div class="sourceCode" id="cb176"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">345</span><span class="op">)</span>

<span class="va">befragung_size</span> <span class="op">&lt;-</span> <span class="fl">200</span>

<span class="va">befragung</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://infer.tidymodels.org/reference/rep_sample_n.html">rep_sample_n</a></span><span class="op">(</span><span class="va">grundgesamtheit</span>, size <span class="op">=</span> <span class="va">befragung_size</span>, replace <span class="op">=</span> <span class="cn">FALSE</span>, reps <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>

<span class="va">befragung</span></code></pre></div>
<pre><code>## # A tibble: 200 x 7
## # Groups:   replicate [1]
##    replicate student_id geschlecht wohnort verkehrsmittel anreise zeit_bib
##        &lt;int&gt;      &lt;int&gt; &lt;chr&gt;      &lt;chr&gt;   &lt;chr&gt;            &lt;dbl&gt;    &lt;dbl&gt;
##  1         1       1623 m          stadt   zu_fuss           7.06     299.
##  2         1       9171 m          stadt   fahrrad          11.3      278.
##  3         1      10207 w          land    bus             107.       199.
##  4         1       3506 w          stadt   bus              25.0      326.
##  5         1       8892 w          stadt   bus              28.1      259.
##  6         1       5460 m          stadt   bus              23.6      299.
##  7         1       6120 w          stadt   bus              20.0      268.
##  8         1        865 w          stadt   fahrrad          26.6      290.
##  9         1      11586 m          land    bus             114.       207.
## 10         1       8153 w          stadt   zu_fuss           8.06     297.
## # … with 190 more rows</code></pre>
<div id="modell-anpassen" class="section level3" number="11.4.1">
<h3>
<span class="header-section-number">11.4.1</span> Modell anpassen<a class="anchor" aria-label="anchor" href="#modell-anpassen"><i class="fas fa-link"></i></a>
</h3>
<p>Wir unterstellen einen linearen Zusammenhang zwischen <code>zeit_bib</code> und <code>anreise</code> und passen ein lineares Modell an. Dazu nutzen wir die Funktion <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>. Sie braucht die Zielvariable und den Prädiktor, die Sie mit Tilde verbunden angeben. Das ist die sogen. <code>formula</code> (Formel, so ähnlich wie eine Matheformel). Die Tilde hatten wir schon so ähnlich bei der Bibliothek <code>infer</code> benutzt. Außerdem müssen wir noch den Datensatz, in dem die Variablen zu finden sind, benennen.</p>
<div class="sourceCode" id="cb178"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lin_mod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">zeit_bib</span> <span class="op">~</span> <span class="va">anreise</span>, data <span class="op">=</span> <span class="va">befragung</span><span class="op">)</span></code></pre></div>
</div>
<div id="modellergebnisse-ansehen" class="section level3" number="11.4.2">
<h3>
<span class="header-section-number">11.4.2</span> Modellergebnisse ansehen<a class="anchor" aria-label="anchor" href="#modellergebnisse-ansehen"><i class="fas fa-link"></i></a>
</h3>
<p>Die Struktur eines solchen linearen Modellobjekts ist richtig kompliziert. Daher gibt es verschiedene Methoden, um aus diesem Objekt sinnvolle Information zu entnehmen.</p>
<div class="sourceCode" id="cb179"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">lin_mod</span><span class="op">)</span></code></pre></div>
<pre><code>## List of 12
##  $ coefficients : Named num [1:2] 302.094 -0.766
##   ..- attr(*, "names")= chr [1:2] "(Intercept)" "anreise"
##  $ residuals    : Named num [1:200] 2.55 -15.31 -21.32 42.64 -21.19 ...
##   ..- attr(*, "names")= chr [1:200] "1" "2" "3" "4" ...
##  $ effects      : Named num [1:200] -3903 -312.5 -24.2 42.7 -21.2 ...
##   ..- attr(*, "names")= chr [1:200] "(Intercept)" "anreise" "" "" ...
##  $ rank         : int 2
##  $ fitted.values: Named num [1:200] 297 293 220 283 281 ...
##   ..- attr(*, "names")= chr [1:200] "1" "2" "3" "4" ...
##  $ assign       : int [1:2] 0 1
##  $ qr           :List of 5
##   ..$ qr   : num [1:200, 1:2] -14.1421 0.0707 0.0707 0.0707 0.0707 ...
##   .. ..- attr(*, "dimnames")=List of 2
##   .. .. ..$ : chr [1:200] "1" "2" "3" "4" ...
##   .. .. ..$ : chr [1:2] "(Intercept)" "anreise"
##   .. ..- attr(*, "assign")= int [1:2] 0 1
##   ..$ qraux: num [1:2] 1.07 1.05
##   ..$ pivot: int [1:2] 1 2
##   ..$ tol  : num 1e-07
##   ..$ rank : int 2
##   ..- attr(*, "class")= chr "qr"
##  $ df.residual  : int 198
##  $ xlevels      : Named list()
##  $ call         : language lm(formula = zeit_bib ~ anreise, data = befragung)
##  $ terms        :Classes 'terms', 'formula'  language zeit_bib ~ anreise
##   .. ..- attr(*, "variables")= language list(zeit_bib, anreise)
##   .. ..- attr(*, "factors")= int [1:2, 1] 0 1
##   .. .. ..- attr(*, "dimnames")=List of 2
##   .. .. .. ..$ : chr [1:2] "zeit_bib" "anreise"
##   .. .. .. ..$ : chr "anreise"
##   .. ..- attr(*, "term.labels")= chr "anreise"
##   .. ..- attr(*, "order")= int 1
##   .. ..- attr(*, "intercept")= int 1
##   .. ..- attr(*, "response")= int 1
##   .. ..- attr(*, ".Environment")=&lt;environment: R_GlobalEnv&gt; 
##   .. ..- attr(*, "predvars")= language list(zeit_bib, anreise)
##   .. ..- attr(*, "dataClasses")= Named chr [1:2] "numeric" "numeric"
##   .. .. ..- attr(*, "names")= chr [1:2] "zeit_bib" "anreise"
##  $ model        :'data.frame':   200 obs. of  2 variables:
##   ..$ zeit_bib: num [1:200] 299 278 199 326 259 ...
##   ..$ anreise : num [1:200] 7.06 11.34 106.81 24.97 28.11 ...
##   ..- attr(*, "terms")=Classes 'terms', 'formula'  language zeit_bib ~ anreise
##   .. .. ..- attr(*, "variables")= language list(zeit_bib, anreise)
##   .. .. ..- attr(*, "factors")= int [1:2, 1] 0 1
##   .. .. .. ..- attr(*, "dimnames")=List of 2
##   .. .. .. .. ..$ : chr [1:2] "zeit_bib" "anreise"
##   .. .. .. .. ..$ : chr "anreise"
##   .. .. ..- attr(*, "term.labels")= chr "anreise"
##   .. .. ..- attr(*, "order")= int 1
##   .. .. ..- attr(*, "intercept")= int 1
##   .. .. ..- attr(*, "response")= int 1
##   .. .. ..- attr(*, ".Environment")=&lt;environment: R_GlobalEnv&gt; 
##   .. .. ..- attr(*, "predvars")= language list(zeit_bib, anreise)
##   .. .. ..- attr(*, "dataClasses")= Named chr [1:2] "numeric" "numeric"
##   .. .. .. ..- attr(*, "names")= chr [1:2] "zeit_bib" "anreise"
##  - attr(*, "class")= chr "lm"</code></pre>
<p>Als erstes sehen wir uns die Zusammenfassung des Modells an. Die nicht tidy-Form enthält sehr viel Information, die man am Anfang gar nicht braucht. Und sie glänzt mit vielen Signifikanz-Sternchen, die wir am liebsten gleich verbannen würden.</p>
<div class="sourceCode" id="cb181"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">lin_mod</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = zeit_bib ~ anreise, data = befragung)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -60.060 -14.063   0.836  15.662  64.151 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 302.09377    2.28190  132.39   &lt;2e-16 ***
## anreise      -0.76627    0.05112  -14.99   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 20.85 on 198 degrees of freedom
## Multiple R-squared:  0.5316, Adjusted R-squared:  0.5292 
## F-statistic: 224.7 on 1 and 198 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Daher empfehle ich die tidy-Form. Wir nutzen die Funktion <code>get_regression_table</code> aus der Bibliothek <code>moderndive</code>, die intern auf die Bibliothek <code>broom</code> zugreift (<a href="https://cran.r-project.org/web/packages/broom/vignettes/broom.html" class="uri">https://cran.r-project.org/web/packages/broom/vignettes/broom.html</a>). <code>broom</code> hilft, die Ausgabe des linearen Modells in eine tidy-Form zu konvertieren. Die Funktion <code><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable()</a></code> aus der Bibliothek <code>knitr</code> layoutet die Tabelle.</p>
<div class="sourceCode" id="cb183"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/moderndive/man/get_regression_table.html">get_regression_table</a></span><span class="op">(</span><span class="va">lin_mod</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std_error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p_value
</th>
<th style="text-align:right;">
lower_ci
</th>
<th style="text-align:right;">
upper_ci
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
intercept
</td>
<td style="text-align:right;">
302.094
</td>
<td style="text-align:right;">
2.282
</td>
<td style="text-align:right;">
132.387
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
297.594
</td>
<td style="text-align:right;">
306.594
</td>
</tr>
<tr>
<td style="text-align:left;">
anreise
</td>
<td style="text-align:right;">
-0.766
</td>
<td style="text-align:right;">
0.051
</td>
<td style="text-align:right;">
-14.990
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
-0.867
</td>
<td style="text-align:right;">
-0.665
</td>
</tr>
</tbody>
</table></div>
<p>Sie sehen in der ersten Spalte <code>(Intercept)</code> und <code>anreise</code>. Das sind der <span class="math inline">\(y\)</span>-Achsenabschnitt <span class="math inline">\(\beta_0\)</span> und die Steigung <span class="math inline">\(\beta_1\)</span> des Modells. Das heißt unser Modell lautet ausgeschrieben:</p>
<p><span class="math display">\[\widehat{\text{zeit_bib}_i} = 302.094 - 0.766 \cdot \text{anreise_i}\]</span>
Der Index <span class="math inline">\(i\)</span> steht hier für die unterschiedlichen Studierenden, denn jede(r) hat natürlich eine eigene Anreise- und Arbeitszeit in der Bibliothek. Wir lernen also, dass mit steigender Anreisezeit, die Arbeitszeit in der Bibliothek sinkt. Und zwar können wir es sogar noch genauer sagen: mit jeder zusätzlichen Minute Anreisezeit, sinkt die Arbeitszeit in der Bibliothek um 0.766 Minuten. Auf die übrigen Spalten kommen wir später zu sprechen.</p>
<p>Welche Werte hat das Modell berechnet? Diese nennt man angepasste Werte (<em>fitted</em>) und man kann sie mit der Funktion <code><a href="https://rdrr.io/r/stats/fitted.values.html">fitted()</a></code> abfragen. Wir sehen uns nur die ersten Einträge an.</p>
<div class="sourceCode" id="cb184"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">lin_mod</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>##        1        2        3        4        5        6 
## 296.6866 293.4026 220.2491 282.9618 280.5521 284.0451</code></pre>
<p>Wir würden gerne diese angepassten Werte mit den echten gemessenen Werten, nämlich der tatsächlichen Arbeitszeit in der Bibliothek, vergleichen. Dafür fügen wir die gemessenen und die angepassten Werte in einem <code>tibble</code> zusammen. Wir erstellen eine neue Spalte mit angepassten Werten und den Residuen, d.h. den Differenzen zwischen den gemessenen und den angepassten Werten.</p>
<div class="sourceCode" id="cb186"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">model_res</span> <span class="op">&lt;-</span> <span class="va">befragung</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>fitted <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">lin_mod</span><span class="op">)</span>, residuals <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">lin_mod</span><span class="op">)</span><span class="op">)</span> </code></pre></div>
<p>Nun können wir die Werte gegeneinander plotten und uns die Residuen ansehen. Diese sind als graue vertikale Linien zwischen den gemessenen und den angepassten Werten dargestellt. Die angepassten Werte liegen alle auf einer Geraden, das ist ja die Quintessenz eines linearen Modells. Zu jedem gemessenen Wert gibt es einen angepassten, modellierten Wert auf der Geraden. Das geom <code>geom_abline</code> zeichnet unsere Gerade.</p>
<div class="sourceCode" id="cb187"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="va">model_res</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">anreise</span>, y <span class="op">=</span> <span class="va">zeit_bib</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_segment</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>xend <span class="op">=</span> <span class="va">anreise</span>, yend <span class="op">=</span> <span class="va">fitted</span>, lty <span class="op">=</span> <span class="st">'Residuen'</span><span class="op">)</span>, alpha <span class="op">=</span> <span class="fl">0.2</span><span class="op">)</span>  <span class="op">+</span> 
  <span class="fu">geom_abline</span><span class="op">(</span>intercept <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">lin_mod</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, slope <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">lin_mod</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>, color <span class="op">=</span> <span class="st">"lightblue"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>col <span class="op">=</span> <span class="st">'observed'</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="va">fitted</span>, col <span class="op">=</span> <span class="st">'fitted'</span><span class="op">)</span>, shape <span class="op">=</span> <span class="fl">1</span>, size <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">'Anreisezeit (min)'</span>, y <span class="op">=</span> <span class="st">'Arbeitszeit in der Bibliothek (min)'</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">scale_color_manual</span><span class="op">(</span>name <span class="op">=</span> <span class="st">''</span>, values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>observed <span class="op">=</span> <span class="st">'black'</span>, fitted <span class="op">=</span> <span class="st">'blue'</span><span class="op">)</span>, breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'observed'</span>, <span class="st">'fitted'</span><span class="op">)</span>, label <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'Gemessene Werte'</span>, <span class="st">'Angepasste Werte'</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">scale_linetype_manual</span><span class="op">(</span>name <span class="op">=</span> <span class="st">''</span>, values <span class="op">=</span> <span class="op">(</span><span class="st">'Residuen'</span> <span class="op">=</span> <span class="st">'solid'</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">'bottom'</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="datenanalyse_files/figure-html/unnamed-chunk-143-1.png" width="90%"></div>
</div>
<div id="modellannahmen-überprüfen" class="section level3" number="11.4.3">
<h3>
<span class="header-section-number">11.4.3</span> Modellannahmen überprüfen<a class="anchor" aria-label="anchor" href="#modellannahmen-%C3%BCberpr%C3%BCfen"><i class="fas fa-link"></i></a>
</h3>
<p>Bei der linearen Regression nehmen wir an, das der Zusammenhang zwischen der Zielvariablen und dem Prädiktor linear ist. Das können wir an der oberen Grafik bereits erkennen. Weiterin nehmen wir an, dass die Residuen im Mittel um die Null schwanken und homoskedastisch sind, d.h. ihre Varianz ist gleich. Diese Annahmen müssen wir überprüfen, bevor es ans Interpretieren der Modellparameter geht. Das macht man hauptsächlich grafisch. Wir plotten die Residuen gegen die angepassten Werte.</p>
<div class="sourceCode" id="cb188"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">model_res</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">fitted</span>, y <span class="op">=</span> <span class="va">residuals</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">0</span>, col <span class="op">=</span> <span class="st">'red'</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">'Angepasste Werte'</span>, y <span class="op">=</span> <span class="st">'Residuen'</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="datenanalyse_files/figure-html/unnamed-chunk-144-1.png" width="90%"></div>
<p>Diese Darstellung der Residuen gegen angepasste Werte nennt man Residualplot. Darin können wir erkennen, dass unsere Residuen um die Null schwanken. Die erste Annahme ist also schon einmal erfüllt. Die Homoskedastizität ist nicht ganz erfüllt. Bei höheren angepassten Werten scheinen die Residuen stärker zu schwanken. Allerdings gibt es nur sehr wenige Werte &lt; 250 Minuten. Daher ist es schwierig, daraus eine echte Heteorskedastizität abzuleiten. Wichtig ist, dass wir keine systematische Zunahme oder Abnahme der Variabilität beobachten und auch keine sonstigen Muster in den Residuen. Die zweite Modellannahme können wir auch als erfüllt abhaken. Wir können plausibel davon ausgehen, dass die Residuen unabhängig sind. Denn wir haben weder eine Zeitreihe gemessen, noch Leute mehrfach befragt.</p>
<p>Die Zusammenfassung des linearen Modells bietet noch weiter Informationen.</p>
<div class="sourceCode" id="cb189"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/moderndive/man/get_regression_table.html">get_regression_table</a></span><span class="op">(</span><span class="va">lin_mod</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std_error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p_value
</th>
<th style="text-align:right;">
lower_ci
</th>
<th style="text-align:right;">
upper_ci
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
intercept
</td>
<td style="text-align:right;">
302.094
</td>
<td style="text-align:right;">
2.282
</td>
<td style="text-align:right;">
132.387
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
297.594
</td>
<td style="text-align:right;">
306.594
</td>
</tr>
<tr>
<td style="text-align:left;">
anreise
</td>
<td style="text-align:right;">
-0.766
</td>
<td style="text-align:right;">
0.051
</td>
<td style="text-align:right;">
-14.990
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
-0.867
</td>
<td style="text-align:right;">
-0.665
</td>
</tr>
</tbody>
</table></div>
<p>Hier gibt es noch die Spalten</p>
<ul>
<li>
<code>std_error</code>: Standardfehler der Schätzung des jeweiligen Modellparameters (intercept oder anreise)</li>
<li>
<code>statistics</code>: Wert der <span class="math inline">\(t\)</span>-Statistik für einen Hypothesentest, der überfüft, ob der jeweilige Modellparameter Null ist. Die Nullhypothese lautet <span class="math inline">\(\beta_0 = 0\)</span> für den <span class="math inline">\(y\)</span>-Achsenabschnitt bzw. <span class="math inline">\(\beta_1 = 0\)</span> für die Steigung. Die Alternativhypothese lautet, dass der jeweilige Modellparameter ungleich Null ist.</li>
<li>
<code>p-value</code>: p-Wert des Hypothesentests</li>
<li>
<code>lower_ci</code>, <code>upper_ci</code>: unterer und oberer Wert des Konfidentintervalls (Standardeinstellung 95%)</li>
</ul>
<p>Für die Berechnung des Standardfehlers, des Hypothesentests und der Konfidenzintervalle wird, zusätzlich zu den oben genannten Annahmen, vorausgesetzt, dass die Residuen normalverteilt sind. Nur wenn sie es tatsächlich sind, sind diese Berechnungen und der Hypothesentest korrekt, sonst möglicherweise nicht. Deswegen müssen wir, bevor wir diese Spalten interpretieren, überprüfen, ob die Residuen normalverteilt sind. Das machen wir mit einem QQ-Plot. Sie dürfen auch noch einen formalen <code><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test()</a></code> machen, wenn Sie möchten.</p>
<div class="sourceCode" id="cb190"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="va">model_res</span>, <span class="fu">aes</span><span class="op">(</span>sample <span class="op">=</span> <span class="va">residuals</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">stat_qq</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">stat_qq_line</span><span class="op">(</span>col <span class="op">=</span> <span class="st">'blue'</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">'Quantile aus der Normalverteilung'</span>,
       y <span class="op">=</span> <span class="st">'Qunatile der Daten'</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="datenanalyse_files/figure-html/unnamed-chunk-146-1.png" width="90%"></div>
<p>Wenn die Residuen normalverteilt sind, dann liegen sie nahe der Geraden im QQ-Plot. Das ist hier der Fall. Die Annahme der Normalverteilung der Residuen ist also erfüllt und wir dürfen den Standardfehler, den p-Wert und die Konfidenzintervalle interpretieren.</p>
</div>
<div id="modell-interpretieren" class="section level3" number="11.4.4">
<h3>
<span class="header-section-number">11.4.4</span> Modell interpretieren<a class="anchor" aria-label="anchor" href="#modell-interpretieren"><i class="fas fa-link"></i></a>
</h3>
<p>In unserem fiktiven Datensatz, nimmt die Arbeitseit in der Bibliothek mit der Anreisezeit ab. Wir haben bereits die Schätzungen des <span class="math inline">\(y\)</span>-Achsenabschnitts (intercept) und der Steigung (anreise) interpretiert. Jetzt können wir zusätzlich sagen, wie gut wir geschätzt haben. Der <span class="math inline">\(y\)</span>-Achsenabschnitt gibt die Anreisezeit in der Bibliothek an, wenn die Anreisezeit Null wäre. Das ist zwar die korrekte Interpretation, aber eine Extrapolation außerhalb unseres Messbereichs der Anreisezeit. Daher sollte man den <span class="math inline">\(y\)</span>-Achsenabschnitt nicht überinterpretieren. Er ist erst einmal ein Modellparameter, der gut geschätzt wurde mit einem Konfidenzintervall von [297.594, 306.594]. Ob die Studierenden tatsächlich diese Zeit in der Bibliothek verbringen würden, wenn sie quasi auf dem Campus wohnen würden, ist eine Spekulation.</p>
<p>Einfacher und sinnvoller ist die Interpretation der Steigung. Ihr Konfidenzintervall lautet [-0.867, -0.665]. Es ist eine gute Schätzung, da das Konfidenzintervall schmal ist. Pro zusätzlicher Anreiseminute sinkt die Arbeitszeit in der Bibliothek um einen Wert in diesem Konfidenzintervall.</p>
<p>Die Hypothesentests können Sie interpretieren, wie gewohnt, müssen Sie aber nicht. Wie in den vorherigen Kapiteln erwähnt, kann man auf den Begriff <em>signifikant</em> getrost verzichten. Die Schätzung der Parameter und deren Konfidenzintervalle bringt sehr viel mehr Information.</p>
Zum Schluss noch die wichtigsten Take-Home Messages.
<div class="rmdalert">
<ul>
<li>
Regression beinhaltet eine große Familie an Modellen.
</li>
<li>
Lineare Regression: linearer Einfluss der Kovariablen auf <span class="math inline"><span class="math inline">\(y\)</span></span>.
</li>
<li>
Annahmen: Residuen <span class="math inline"><span class="math inline">\(\varepsilon_i\)</span></span> sind iid mit <span class="math display"><span class="math display">\[\mathrm{E}(\varepsilon_i) = 0, \qquad \mathrm{Var}(\varepsilon_i)=\sigma^2.\]</span></span>
</li>
<li>
Normalregression zusätzlich: <span class="math inline"><span class="math inline">\(\varepsilon_i \sim N(0,\sigma^2)\)</span></span>.
</li>
<li>
Überprüfung der Annahmen (vor allem) grafisch.
</li>
<li>
Konfidenzintervalle und Hypothesentests der Normalregression dürfen nur dann interpretiert werden, wenn die Annahmen erfüllt sind.
</li>
</ul>
</div>
</div>
</div>
<div id="lesestoff-9" class="section level2" number="11.5">
<h2>
<span class="header-section-number">11.5</span> Lesestoff<a class="anchor" aria-label="anchor" href="#lesestoff-9"><i class="fas fa-link"></i></a>
</h2>
<p>Kapitel 5 in <span class="citation"><a href="literatur.html#ref-ModernDive" role="doc-biblioref">Ismay and Kim</a> (<a href="literatur.html#ref-ModernDive" role="doc-biblioref">2021</a>)</span></p>
</div>
<div id="aufgaben-8" class="section level2" number="11.6">
<h2>
<span class="header-section-number">11.6</span> Aufgaben<a class="anchor" aria-label="anchor" href="#aufgaben-8"><i class="fas fa-link"></i></a>
</h2>
<div id="kategorielle-variable-als-prädiktor" class="section level3" number="11.6.1">
<h3>
<span class="header-section-number">11.6.1</span> Kategorielle Variable als Prädiktor<a class="anchor" aria-label="anchor" href="#kategorielle-variable-als-pr%C3%A4diktor"><i class="fas fa-link"></i></a>
</h3>
<p>Arbeiten Sie selbständig das Beispiel in Kapitel 5.2 in <span class="citation"><a href="literatur.html#ref-ModernDive" role="doc-biblioref">Ismay and Kim</a> (<a href="literatur.html#ref-ModernDive" role="doc-biblioref">2021</a>)</span> durch.</p>
<!-- ## Ihre Arbeit einreichen -->
<!-- - Speichern Sie Ihr Notebook ab und laden Sie nur die .Rmd Datei vom Server. -->
<!-- - Laden Sie Ihre .Rmd Datei in ILIAS hoch. **Beachten Sie die Deadline!** -->
<!-- - Sie erhalten die Musterlösung nach dem Hochladen. -->

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="effekte.html"><span class="header-section-number">10</span> Schätzen von Effekten: Raus aus der \(p &lt; 0.05\)-Falle</a></div>
<div class="next"><a href="regression-inferenz.html"><span class="header-section-number">12</span> Inferenz in linearer Regression</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#regression"><span class="header-section-number">11</span> Lineare Regression</a></li>
<li><a class="nav-link" href="#begriff-regression"><span class="header-section-number">11.1</span> Begriff Regression</a></li>
<li><a class="nav-link" href="#idee-der-regression"><span class="header-section-number">11.2</span> Idee der Regression</a></li>
<li><a class="nav-link" href="#einfache-lineare-regression"><span class="header-section-number">11.3</span> Einfache lineare Regression</a></li>
<li>
<a class="nav-link" href="#beispiel-zusammenhang-zwischen-der-anreisezeit-und-der-arbeitszeit-in-der-bibliothek"><span class="header-section-number">11.4</span> Beispiel: Zusammenhang zwischen der Anreisezeit und der Arbeitszeit in der Bibliothek</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#modell-anpassen"><span class="header-section-number">11.4.1</span> Modell anpassen</a></li>
<li><a class="nav-link" href="#modellergebnisse-ansehen"><span class="header-section-number">11.4.2</span> Modellergebnisse ansehen</a></li>
<li><a class="nav-link" href="#modellannahmen-%C3%BCberpr%C3%BCfen"><span class="header-section-number">11.4.3</span> Modellannahmen überprüfen</a></li>
<li><a class="nav-link" href="#modell-interpretieren"><span class="header-section-number">11.4.4</span> Modell interpretieren</a></li>
</ul>
</li>
<li><a class="nav-link" href="#lesestoff-9"><span class="header-section-number">11.5</span> Lesestoff</a></li>
<li>
<a class="nav-link" href="#aufgaben-8"><span class="header-section-number">11.6</span> Aufgaben</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#kategorielle-variable-als-pr%C3%A4diktor"><span class="header-section-number">11.6.1</span> Kategorielle Variable als Prädiktor</a></li></ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/ChrisBogner/datenanalyse/blob/master/11-regression.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/ChrisBogner/datenanalyse/edit/master/11-regression.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Datenanalyse mit R</strong>: SoSe 2021" was written by Christina Bogner. It was last built on 2021-06-30.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>
</html>
